"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { BookOpen, Heart, Sparkles, Star, Users, Clock } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function ChildrenStoriesPage() {
  const router = useRouter();

  const storyTypes = [
    {
      title: "Bedtime Stories",
      description: "Gentle, soothing tales perfect for bedtime routine",
      keywords: "bedtime stories AI, children's bedtime stories, AI bedtime story generator",
      icon: <Clock className="h-8 w-8" />,
      gradient: "from-blue-400 to-indigo-500",
      examples: ["The Sleepy Dragon", "Moonbeam's Adventure", "The Dream Catcher"]
    },
    {
      title: "Educational Stories",
      description: "Learn through fun adventures and moral lessons",
      keywords: "educational children's stories, learning stories for kids, AI educational content",
      icon: <Star className="h-8 w-8" />,
      gradient: "from-green-400 to-emerald-500",
      examples: ["Math Adventure", "Science Explorer", "History Heroes"]
    },
    {
      title: "Animal Stories",
      description: "Adventures featuring adorable animal characters",
      keywords: "animal stories for children, AI animal tales, kids animal stories",
      icon: <Heart className="h-8 w-8" />,
      gradient: "from-pink-400 to-rose-500",
      examples: ["Bunny's Garden", "The Brave Bear", "Cat's Big Day"]
    },
    {
      title: "Fantasy Adventures",
      description: "Magical worlds and enchanted journeys",
      keywords: "fantasy children's stories, magic stories for kids, AI fantasy tales",
      icon: <Sparkles className="h-8 w-8" />,
      gradient: "from-purple-400 to-violet-500",
      examples: ["The Wizard's Apprentice", "Fairy Tale Kingdom", "Dragon's Quest"]
    }
  ];

  const benefits = [
    "Age-appropriate content tailored to child development",
    "Interactive storytelling that engages young minds",
    "Educational value with fun storytelling",
    "Safe, family-friendly narratives",
    "Customizable characters and settings",
    "Instant generation for bedtime emergencies!"
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 dark:from-slate-900 dark:via-blue-900/20 dark:to-purple-900/20">
      {/* Hero Section */}
      <section className="relative py-16 md:py-24">
        <div className="container px-4 md:px-6 max-w-6xl mx-auto">
          <div className="text-center space-y-6">
            <Badge className="bg-gradient-to-r from-blue-500 to-purple-500 text-white px-4 py-2 text-sm font-semibold">
              AI-Powered Children's Stories
            </Badge>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-extrabold tracking-tight">
              <span className="bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">
                Children's Stories
              </span>
              <br />
              <span className="text-slate-800 dark:text-white">
                Generated by AI
              </span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
              Create magical, personalized children's stories with our AI story generator. 
              From bedtime tales to educational adventures, generate unique narratives that 
              engage and inspire young minds instantly.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                onClick={() => router.push('/create-story-book')}
                className="bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white px-8 py-3 text-lg font-semibold rounded-xl shadow-lg hover:shadow-xl transition-all duration-300"
              >
                <BookOpen className="mr-2 h-5 w-5" />
                Start Creating Stories
              </Button>
              <Button 
                variant="outline" 
                onClick={() => router.push('/story-book')}
                className="px-8 py-3 text-lg font-semibold rounded-xl border-2 hover:bg-blue-50"
              >
                Browse Examples
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Story Types Section */}
      <section className="py-16 bg-white/50 dark:bg-slate-800/50">
        <div className="container px-4 md:px-6 max-w-6xl mx-auto">
          <div className="text-center space-y-4 mb-12">
            <h2 className="text-3xl md:text-4xl font-bold">Types of Children's Stories</h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Discover the perfect story type for every occasion and developmental stage
            </p>
          </div>
          
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            {storyTypes.map((type, index) => (
              <Card key={type.title} className="group hover:shadow-xl transition-all duration-300 border-0 bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm">
                <CardHeader className="text-center">
                  <div className={`inline-flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-r ${type.gradient} shadow-lg mx-auto mb-4 group-hover:scale-110 transition-transform duration-300`}>
                    <div className="text-white">
                      {type.icon}
                    </div>
                  </div>
                  <CardTitle className="text-xl font-bold">{type.title}</CardTitle>
                  <CardDescription className="text-sm text-muted-foreground leading-relaxed">
                    {type.description}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">Popular Examples:</p>
                    {type.examples.map((example, i) => (
                      <div key={i} className="flex items-center gap-2">
                        <div className={`w-2 h-2 rounded-full bg-gradient-to-r ${type.gradient}`} />
                        <p className="text-sm text-muted-foreground">{example}</p>
                      </div>
                    ))}
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    {type.keywords.split(',')[0]}
                  </Badge>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-16">
        <div className="container px-4 md:px-6 max-w-4xl mx-auto">
          <div className="text-center space-y-4 mb-12">
            <h2 className="text-3xl md:text-4xl font-bold">Why Choose AI for Children's Stories?</h2>
            <p className="text-lg text-muted-foreground">
              Experience the future of storytelling for young readers
            </p>
          </div>
          
          <div className="grid gap-6 md:grid-cols-2">
            {benefits.map((benefit, index) => (
              <div key={index} className="flex items-start gap-4 p-4 rounded-xl bg-white/60 dark:bg-slate-800/60 backdrop-blur-sm border border-white/20">
                <div className="w-6 h-6 rounded-full bg-gradient-to-r from-blue-500 to-purple-500 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <div className="w-2 h-2 rounded-full bg-white" />
                </div>
                <p className="text-slate-700 dark:text-slate-300 leading-relaxed">{benefit}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500">
        <div className="container px-4 md:px-6 max-w-4xl mx-auto text-center">
          <div className="space-y-6 text-white">
            <h2 className="text-3xl md:text-4xl font-bold">
              Ready to Create Amazing Children's Stories?
            </h2>
            <p className="text-lg md:text-xl text-blue-100 max-w-2xl mx-auto">
              Join thousands of parents, teachers, and storytellers who use Story AI 
              to create engaging, personalized stories for children.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg"
                onClick={() => router.push('/create-story-book')}
                className="bg-white text-purple-600 hover:bg-blue-50 px-8 py-4 text-lg font-semibold rounded-xl shadow-lg hover:shadow-xl transition-all duration-300"
              >
                <Users className="mr-2 h-5 w-5" />
                Start Creating Now
              </Button>
              <Button 
                size="lg"
                variant="outline"
                onClick={() => router.push('/credits')}
                className="border-white text-white hover:bg-white/10 px-8 py-4 text-lg font-semibold rounded-xl"
              >
                View Pricing
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* SEO Content Section */}
      <section className="py-16 bg-white dark:bg-slate-900">
        <div className="container px-4 md:px-6 max-w-4xl mx-auto">
          <div className="prose prose-lg dark:prose-invert max-w-none">
            <h2>AI Children's Story Generator - Frequently Asked Questions</h2>
            
            <h3>What makes Story AI perfect for children's stories?</h3>
            <p>
              Our AI story generator is specifically designed with children's development in mind. 
              Each story is crafted to be age-appropriate, educational, and engaging while promoting 
              positive values and imagination.
            </p>

            <h3>Can I customize stories for my child?</h3>
            <p>
              Absolutely! You can choose characters, settings, themes, and even include your child's 
              name in the stories. Our AI adapts the complexity and content based on the child's age 
              and interests.
            </p>

            <h3>Are AI-generated children's stories safe?</h3>
            <p>
              Yes, all stories generated by Story AI follow strict content guidelines to ensure they 
              are family-friendly, educational, and promote positive values. No inappropriate content 
              is ever generated.
            </p>

            <h3>How quickly can I generate a children's story?</h3>
            <p>
              Most stories are generated within 30-60 seconds. Perfect for bedtime stories when your 
              child asks for "just one more story!"
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

export default ChildrenStoriesPage;
